### ISSUE TITLE
komentarz

### ISSUE THREAD

**Issue by renatapro** [renatapro/zadanie9#1]
- nie wiem czy dobrze zrobiłam te branche - założyłam je na githubie a nie poprzez git,
jak podłączyłam moje zadania to zniknęły z mojego desktopa - czy to tak ma być??
- jak jest źle to mogę jeszcze raz od nowa robić to repozytorium;
- a jeśli chodzi o zadania - to mam wątpliwości do zadania9.1, nie rozumiem po co są stworzone te zmienne var Triangle1Area
-i zadanie 9.2 czy ten warunek jest ok?

**Comment by zdolny** [comment]
ad. 1. Jest dobrze :) https://scr.hu/wq1GWv
ad. 3. 
W zad. 9.1 to dziala tak:
`var triangle1Area = getTriangleArea(10, 15);` wywolujesz funkcje `getTriangleArea` przekazujac do niej parametry 10 i 15, a wynik dzialania funkcji zostaje przypisany do zmiennej `triangle1Area`
W zad. 9.2 wyglada na to, ze warunek jest ok

utworz teraz dla kazdego brancha pull request na githubie https://scr.hu/q31Zz3
